In [3]:
import numpy as np

In [9]:
arr1d = np.array([1,2,3,4,5], dtype=int)
print("array:", arr1d)
print("boyut (ndim):", arr1d.ndim)
print("eleman sayısı (size):", arr1d.size)
print("şekil (shape):", arr1d.shape)

array: [1 2 3 4 5]
boyut (ndim): 1
eleman sayısı (size): 5
şekil (shape): (5,)


In [11]:
arr2d = np.array([[1,2,3],[4,5,6]])
print("array:", arr2d)
print("boyut(ndim):", arr2d.ndim)
print("eleman sayısı (size):", arr2d.size)
print("şekil(shape):", arr2d.shape)

array: [[1 2 3]
 [4 5 6]]
boyut(ndim): 2
eleman sayısı (size): 6
şekil(shape): (2, 3)


In [15]:
arr3d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("array:", arr3d)
print("boyut(ndim):", arr3d.ndim)
print("eleman sayısı(size):", arr3d.size)
print("şekil(shape):", arr3d.shape)

array: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
boyut(ndim): 2
eleman sayısı(size): 12
şekil(shape): (4, 3)


In [17]:
print("ikinci satır, üçüncü sütundaki eleman:", arr2d[1,2])
print("ikinci satır:", arr2d[1,:])
print("birinci sütun:", arr2d[:,0])

ikinci satır, üçüncü sütundaki eleman: 6
ikinci satır: [4 5 6]
birinci sütun: [1 4]


In [19]:
arr3d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
zeros_array = np.zeros((2,3), dtype=int)
print("sıfırlardan oluşan array:", zeros_array)
ones_array = np.ones((2,3), dtype=int)
print("birlerden oluşan array:", ones_array)

sıfırlardan oluşan array: [[0 0 0]
 [0 0 0]]
birlerden oluşan array: [[1 1 1]
 [1 1 1]]


In [39]:
satir_birlestirme = np.vstack((zeros_array,ones_array))
print("satır birleştirilmiş array:", satir_birlestirme)

satır birleştirilmiş array: [[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]


In [41]:
sutun_birlestirme = np.hstack((zeros_array,ones_array))
print("sütün birleştirilmiş array:", sutun_birlestirme)

sütün birleştirilmiş array: [[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
